### ISSUE TITLE
Problem with image tag

### ISSUE THREAD

**Issue by johannesnagl** [bustardcelly/gulp-rev-append#1]
Hi!

I love your gulp-plugin, but I found the following problem:

When rev-ing the following line:

```html
<img src="img/file.png?rev=@@" class="pull-right company-logo media-object">
```

all attributes after the src are deleted:

```html
<img src="img/file.png?rev=1e5d102310e67cbffa59120aaa32f3a0">
```

Quickfix for now: move the class attribute before the src attribute. than the rev-ing is working as expected.

**Comment by bustardcelly** [comment]
Supported test with latest in developer branch to confirm that fixed/non-issue.
