### ISSUE TITLE
Problem with img-inline-code 

### ISSUE THREAD

**Issue by johannesnagl** [bustardcelly/gulp-rev-append#2]
Hi!

When inlining an image into another tag, the rev-ing is not working at all:

Not working:

```html
<a href="https://link"><img src="img/file.png?rev=@@"></a>
```

Working:

```html
<a href="https://link">
  <img src="img/file.png?rev=@@">
</a>
```

**Comment by bustardcelly** [comment]
Supported test with latest in developer branch to confirm that fixed/non-issue.
